import { Link } from 'react-router-dom'
import { dateLabel, execution, offensiveTime, percentLabel, statistics, statusLabels } from '../../../domain/tracking'
import type { TrackingData } from '../api'
import { Bar, ExecutionRing, Metric } from '../components'

export function Dashboard({ data }: { data: TrackingData }) {
  const { offensive, today } = data
  if (!offensive) return <section className="panel welcome-panel"><div className="welcome-mark" aria-hidden="true">↗</div><p className="eyebrow">COMECE PELO SEU PERÍODO</p><h2>O primeiro passo é definir sua ofensiva.</h2><p>Escolha uma data de início e por quantos dias quer acompanhar sua consistência. Depois, adicione as atividades que fazem parte da sua rotina.</p><Link className="button primary" to="/offensives">Criar minha ofensiva →</Link><div className="welcome-steps"><span>01 · Defina seu período</span><span>02 · Planeje suas atividades</span><span>03 · Registre seu dia</span></div></section>
  const time = offensiveTime(offensive, today)
  const stats = statistics(data.summaries, today)
  const daily = execution(data.logs)
  const chart = [...data.summaries].sort((a, b) => a.day.localeCompare(b.day)).slice(-30)
  const journeys = data.journeys.filter(item => item.status !== 'archived').slice(0, 3)
  const overdue = data.tasks.filter(item => item.status !== 'completed' && item.status !== 'archived' && item.due_date && item.due_date < today)
  return <>
    <section className="offensive-banner"><div><p className="eyebrow">{statusLabels[offensive.status]} · {offensive.duration_days} DIAS</p><h2>{offensive.name}</h2><p>{dateLabel(offensive.start_date, true)} — {dateLabel(offensive.end_date, true)}</p></div><div className="offensive-clock"><strong>{today < offensive.start_date ? 'Ainda não começou' : today > offensive.end_date ? 'Período encerrado' : `Dia ${time.current}`}<small>{today >= offensive.start_date && today <= offensive.end_date ? ` / ${offensive.duration_days}` : ''}</small></strong><Bar value={time.temporal} label="Tempo transcorrido" /><span>{percentLabel(time.temporal)} do tempo · {time.remaining} dias restantes</span></div></section>
    <div className="metrics-grid"><Metric label="Média de execução" value={percentLabel(stats.average)} detail="Dias encerrados com planejamento" /><Metric label="Sequência atual" value={<>{stats.streak}<small> dias</small></>} detail={`Melhor sequência: ${stats.best} dias`} /><Metric label="Esta semana" value={percentLabel(stats.week)} detail="Segunda a domingo · dias encerrados" /><Metric label="Este mês" value={percentLabel(stats.month)} detail="Dias encerrados da ofensiva" /></div>
    <div className="dashboard-columns"><section className="panel chart-panel"><div className="section-heading"><div><h2>Consistência ao longo do tempo</h2><p>Execução diária · últimos {chart.length} dias do período</p></div><span className="legend"><i />Execução</span></div>
      {chart.length ? <div className="chart" role="img" aria-label="Gráfico de execução diária. Valores disponíveis na lista de dias abaixo.">{chart.map(row => <div className={`chart-column ${row.day === today ? 'current-day' : ''}`} key={row.day}><div className={`chart-bar ${row.execution_percent === null ? 'unplanned' : ''}`} style={{ height: `${Math.max(Number(row.execution_percent) || 0, 2)}%` }} title={`${dateLabel(row.day, true)}: ${row.execution_percent === null ? 'Sem planejamento' : percentLabel(Number(row.execution_percent))}${row.day === today ? ' · parcial' : ''}`} /><span>{row.day.slice(-2)}</span></div>)}</div> : <p className="empty-copy">O histórico começa na data inicial da ofensiva.</p>}
      <details className="chart-data"><summary>Ver valores por dia</summary><ul>{chart.map(row => <li key={row.day}>{dateLabel(row.day, true)} <strong>{row.execution_percent === null ? 'Sem planejamento' : percentLabel(Number(row.execution_percent))}{row.day === today ? ' · parcial' : ''}</strong></li>)}</ul></details>
      <div className="day-counts"><span><b>{stats.perfect}</b> completos</span><span><b>{stats.partial}</b> parciais</span><span><b>{stats.zero}</b> sem execução</span><span><b>{stats.unplanned}</b> sem planejamento</span></div>
    </section><section className="panel today-card"><div className="section-heading"><h2>Seu dia, hoje</h2><span className="pill">Parcial</span></div><ExecutionRing value={daily.percent} /><p>{daily.planned ? `${daily.completed} de ${daily.planned} atividades concluídas` : 'Sem atividades planejadas'}</p><Link className="button primary" to="/today">Abrir Hoje →</Link></section></div>
    <div className="dashboard-columns"><section className="panel"><div className="section-heading"><div><h2>Jornadas</h2><p>Progresso de longo prazo, separado da consistência diária</p></div><Link className="text-link" to="/journeys">Ver todas →</Link></div>{journeys.length ? <div className="journey-progress">{journeys.map(item => { const steps = data.journeySteps.filter(step => step.journey_id === item.id); const value = steps.length ? steps.filter(step => step.status === 'completed').length / steps.length * 100 : 0; return <div key={item.id}><div><strong>{item.name}</strong><span>{percentLabel(value)}</span></div><Bar value={value} label={`Progresso de ${item.name}`} /></div> })}</div> : <p className="empty-copy">Nenhuma jornada ativa. Crie uma para acompanhar metas que não pertencem à rotina diária.</p>}</section><section className="panel"><h2>Em foco</h2><div className="focus-line"><span>Jornadas ativas</span><strong>{data.journeys.filter(item => item.status === 'in_progress').length}</strong></div><div className="focus-line"><span>Tarefas atrasadas</span><strong>{overdue.length}</strong></div><div className="focus-line"><span>Dias decorridos</span><strong>{time.elapsed}</strong></div><p className="muted compact">O tempo segue passando. A execução mostra como você aproveitou os dias planejados.</p></section></div>
  </>
}
